; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:dake_h743]
platform = ststm32
board = dakefpv_h743pro
framework = arduino

upload_protocol = dfu
monitor_speed = 115200

board_build.variants_dir = variants

build_unflags =
    -D HSE_VALUE=25000000

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -D HSE_VALUE=8000000

lib_deps =
  tomstewart89/BasicLinearAlgebra@^5.1
